site: Tocatl Cardano Pool
url: https://tocatl.github.io
title: Tocatl Cardano Pool
description: Working to create a carbon-neutral crypto ecosystem. Multi-layer security running on dedicated hardware. 
50% margin donated to carbon offset and environmental causes. 50% into extra rewards for stakers ($ATL)
twitter:
  username: tocatl
  card: summary

permalink: pretty

paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "updates"
    values:
      layout: "update"
      
  - scope:
      path: "assets/images"
    values:
      image: true
