site: Atocatl Cardano Pool
url: https://atocatl.github.io
title: Atocatl Cardano Pool
description: >
  Atocatl Cardano Pool -
  working to create a carbon-neutral crypto ecosystem. 
  50% margin donated to carbon offset and environmental causes.

twitter:
  username: atocatl
  card: summary

permalink: pretty

paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  updates:
    output: true
    permalink: /updates/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "updates"
    values:
      layout: "update"
      
  - scope:
      path: "assets/images"
    values:
      image: true
